#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "0.3.3"
__short_description__ = "polars_writer is a library that enables JSON-based configuration of Polars DataFrame writing methods, facilitating language-agnostic data export for end-user facing data products. "
__license__ = "MIT"
__author__ = "Sanhe Hu"
__author_email__ = "husanhe@email.com"
__maintainer__ = "Sanhe Hu"
__maintainer_email__ = "husanhe@email.com"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
